### ISSUE TITLE
Nice file names in prj

### ISSUE THREAD

**Issue by Alexey-T** [skalogryz/editorConfig#1]
Why not name source files like EditorConfigNnn.pas ?

**Comment by skalogryz** [comment]
or ECnnnn.pas... once structure is settled, it would be possible to finalize unit names as well.

**Comment by Alexey-T** [comment]
EC is my Econtrol repo files

**Comment by skalogryz** [comment]
please, don't be so selfish xD

until there's a release, the name prefix could be ..selected.

**Comment by Alexey-T** [comment]
EC is used, I mean, EdConfig is not

**Comment by skalogryz** [comment]
all files are now editorconfigXXXX

**Comment by Alexey-T** [comment]
thank you.
